// Phase 3 of the SEO Audit (and a general "finalize" endpoint for any
// streamed action): persist the analysis to KV in a separate request.
//
// Why this exists: /run streams Claude (15-50s) and the appendHistory call
// that used to follow the stream was getting killed by Vercel's 60s function
// timeout before completing — meaning nothing ever made it into KV. By
// splitting the save into its own endpoint, the KV write (~100ms) is no
// longer racing the Claude stream against the timeout.

import { NextResponse } from "next/server";
import { findAction } from "@/lib/seo-pillars";
import { appendHistory } from "@/lib/action-history";
import { loadAuditPrep, clearAuditPrep } from "@/lib/audit-prep-store";
import {
  loadKwResearchPrep,
  clearKwResearchPrep,
} from "@/lib/kw-research-prep-store";
import { parseClustersFromMarkdown } from "@/lib/kw-cluster-parser";
import { enrichKeywordsComprehensive } from "@/lib/seo-tools/keyword-research";
import {
  extractExternalUrls,
  verifyExternalUrls,
  renderBrokenLinkWarning,
} from "@/lib/verify-external-links";

export const runtime = "nodejs";
// Vercel Pro — 300s. /save fires the bulk DataforSEO enrich for the
// AI-cluster keywords inferred from the onboarding form; 40-60 keyword
// lookups in one call can chain past the legacy 60s cap.
export const maxDuration = 300;

const MODEL_ID = "claude-sonnet-4-6";

export async function POST(
  req: Request,
  ctx: { params: Promise<{ clientSlug: string; actionSlug: string }> },
) {
  const { clientSlug, actionSlug } = await ctx.params;

  const entry = findAction(actionSlug);
  if (!entry) {
    return NextResponse.json({ error: "Unknown action" }, { status: 404 });
  }

  let body: {
    resultId?: string;
    inputs?: Record<string, string>;
    output?: string;
    model?: string;
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const resultId = body.resultId;
  const inputs = body.inputs ?? {};
  let output = (body.output ?? "").trim();
  const model = body.model ?? MODEL_ID;

  // Post-stream URL verification for the Blog Article Writer Pro.
  // Every external markdown link is HEAD-checked in parallel; any
  // broken link gets surfaced in a warning callout prepended to the
  // saved output so the consultant sees it before sending the article
  // for client review. Bounded to 6s total to protect the 60s budget.
  if (actionSlug === "write-blog-article" && output.length > 0) {
    try {
      const urls = extractExternalUrls(output);
      if (urls.length > 0) {
        const checks = await Promise.race([
          verifyExternalUrls(urls, { timeoutMs: 4000, concurrency: 8 }),
          new Promise<null>((resolve) => setTimeout(() => resolve(null), 6000)),
        ]);
        if (checks) {
          const warning = renderBrokenLinkWarning(checks);
          if (warning) output = warning + output;
        }
      }
    } catch (err) {
      console.error("link verification failed (non-fatal):", err);
    }
  }

  if (!resultId) {
    return NextResponse.json({ error: "resultId required" }, { status: 400 });
  }
  if (!output) {
    return NextResponse.json(
      { error: "output required (empty after trim)" },
      { status: 400 },
    );
  }

  // Pull whichever structured prep was generated by the run phase.
  let metrics = undefined;
  let vitals = undefined;
  let kwResearch = undefined;
  if (actionSlug === "seo-audit") {
    const prep = await loadAuditPrep(clientSlug, actionSlug, resultId);
    if (prep && prep.status === "ok") {
      metrics = prep.metrics ?? undefined;
      vitals = prep.vitals ?? undefined;
    }
  } else if (actionSlug === "keyword-research") {
    const pack = await loadKwResearchPrep(clientSlug, actionSlug, resultId);
    if (pack) kwResearch = pack;
  }

  // Parse Claude's cluster tables out of the markdown so the dashboard
  // can render them as first-class rows.
  const kwClusters =
    actionSlug === "keyword-research" ? parseClustersFromMarkdown(output) : [];

  // Enrich every cluster keyword with real DataforSEO volume/KD. Claude
  // infers a much wider keyword universe than DataforSEO surfaces in the
  // per-seed pulls (often 40-60 keywords vs 7-15 raw rows), so most
  // cluster rows arrive with vol=null, KD=null. The comprehensive
  // enricher tries three DataforSEO endpoints (Labs overview, bulk KD,
  // Google Ads volume) so cluster rows arrive with both fields populated
  // wherever DataforSEO has the data.
  if (kwClusters.length > 0 && kwResearch) {
    const allClusterKeywords = kwClusters.flatMap((c) =>
      c.rows.map((r) => r.keyword),
    );
    if (allClusterKeywords.length > 0) {
      const enrichment = await enrichKeywordsComprehensive(
        allClusterKeywords,
        kwResearch.geo.locationCode,
        kwResearch.geo.languageCode,
      );
      for (const cluster of kwClusters) {
        for (const row of cluster.rows) {
          const hit = enrichment.get(row.keyword.toLowerCase());
          if (!hit) continue;
          if ((row.volume === null || row.volume === undefined) && hit.searchVolume !== null) {
            row.volume = hit.searchVolume;
            row.volumeText = hit.searchVolume.toString();
          }
          if (
            (row.difficulty === null || row.difficulty === undefined || row.difficulty === 0) &&
            hit.difficulty !== null
          ) {
            row.difficulty = hit.difficulty;
            row.difficultyText = hit.difficulty.toString();
          }
        }
      }
    }
  }

  try {
    const saved = await appendHistory({
      id: resultId,
      clientSlug,
      actionSlug,
      inputs,
      output,
      model,
      ...(metrics ? { metrics } : {}),
      ...(vitals ? { vitals } : {}),
      ...(kwResearch ? { kwResearch } : {}),
      ...(kwClusters.length > 0 ? { kwClusters } : {}),
    });
    if (actionSlug === "seo-audit") {
      await clearAuditPrep(clientSlug, actionSlug, resultId);
    } else if (actionSlug === "keyword-research") {
      await clearKwResearchPrep(clientSlug, actionSlug, resultId);
    }
    return NextResponse.json({
      ok: true,
      id: saved.id,
      metrics: saved.metrics ?? null,
      kwResearch: saved.kwResearch ?? null,
      kwClusters: saved.kwClusters ?? null,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json(
      { error: `Persist failed: ${message}` },
      { status: 500 },
    );
  }
}
